const mongoose = require('mongoose');

const messageSchema = new mongoose.Schema({
  participants: [{
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    role: {
      type: String,
      enum: ['customer', 'showroom', 'admin'],
      required: true
    },
    lastReadAt: Date,
    hasLeft: { type: Boolean, default: false }
  }],
  vehicleId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Vehicle',
    required: true
  },
  messages: [{
    sender: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    content: {
      type: String,
      required: true,
      trim: true,
      maxlength: 2000
    },
    type: {
      type: String,
      enum: ['inquiry', 'response', 'appointment_request', 'negotiation', 'general', 'system'],
      default: 'general'
    },
    attachments: [{
      type: {
        type: String,
        enum: ['image', 'document', 'video', 'audio']
      },
      url: String,
      fileName: String,
      fileSize: Number,
      thumbnail: String,
      duration: Number // for audio/video in seconds
    }],
    metadata: {
      templateUsed: String,
      originalInquiryId: mongoose.Schema.Types.ObjectId,
      relatedAppointmentId: mongoose.Schema.Types.ObjectId,
      offerAmount: Number,
      autoGenerated: { type: Boolean, default: false }
    },
    status: {
      type: String,
      enum: ['sent', 'delivered', 'read', 'failed'],
      default: 'sent'
    },
    readAt: Date,
    deliveredAt: Date,
    createdAt: { type: Date, default: Date.now }
  }],
  status: {
    type: String,
    enum: ['active', 'archived', 'blocked', 'reported'],
    default: 'active'
  },
  priority: {
    type: String,
    enum: ['low', 'normal', 'high', 'urgent'],
    default: 'normal'
  },
  tags: [String],
  analytics: {
    responseTime: Number, // Average response time in minutes
    messageCount: { type: Number, default: 0 },
    lastActivity: Date,
    scheduledForFollowUp: Date,
    conversionStatus: {
      type: String,
      enum: ['in_progress', 'appointment_scheduled', 'test_drive_completed', 'negotiation_started', 'deal_closed', 'lost']
    }
  },
  settings: {
    autoTranslate: { type: Boolean, default: false },
    preferredLanguage: { type: String, default: 'en' },
    notificationsEnabled: { type: Boolean, default: true }
  },
  notes: [{
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    content: String,
    isInternal: { type: Boolean, default: true },
    createdAt: { type: Date, default: Date.now }
  }],
  lastMessage: {
    content: String,
    sender: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    timestamp: Date,
    type: String
  }
}, {
  timestamps: true
});

// Indexes for better performance
messageSchema.index({ 'participants.user': 1 });
messageSchema.index({ vehicleId: 1 });
messageSchema.index({ status: 1 });
messageSchema.index({ 'messages.createdAt': -1 });
messageSchema.index({ 'analytics.lastActivity': -1 });
messageSchema.index({ priority: 1 });
messageSchema.index({ tags: 1 });

// Compound indexes
messageSchema.index([
  { 'participants.user': 1, status: 1 }
]);
messageSchema.index([
  { vehicleId: 1, status: 1, 'analytics.lastActivity': -1 }
]);

// Virtual for unread message count
messageSchema.virtual('unreadCount').get(function() {
  if (!this.lastMessageAt) return 0;
  return this.messages.filter(msg =>
    !msg.readAt &&
    !this.participants.some(p =>
      p.user.toString() === msg.sender.toString() && p.lastReadAt &&
      p.lastReadAt > msg.createdAt
    )
  ).length;
});

// Pre-save middleware to update analytics
messageSchema.pre('save', function(next) {
  if (this.isModified('messages')) {
    this.analytics.messageCount = this.messages.length;
    this.analytics.lastActivity = new Date();

    // Update last message info
    const lastMsg = this.messages[this.messages.length - 1];
    if (lastMsg) {
      this.lastMessage = {
        content: lastMsg.content,
        sender: lastMsg.sender,
        timestamp: lastMsg.createdAt,
        type: lastMsg.type
      };
    }
  }
  next();
});

// Instance methods
messageSchema.methods.addMessage = function(messageData) {
  const message = {
    ...messageData,
    createdAt: new Date()
  };

  this.messages.push(message);
  this.analytics.messageCount = this.messages.length;
  this.analytics.lastActivity = new Date();

  return this.save();
};

messageSchema.methods.markAsRead = function(userId) {
  const participant = this.participants.find(p => p.user.toString() === userId);
  if (participant) {
    participant.lastReadAt = new Date();
  }

  // Mark messages as read
  this.messages.forEach(msg => {
    if (msg.sender.toString() !== userId && !msg.readAt) {
      msg.readAt = new Date();
      msg.status = 'read';
    }
  });

  return this.save();
};

messageSchema.methods.getUnreadCount = function(userId) {
  const participant = this.participants.find(p => p.user.toString() === userId);
  if (!participant || !participant.lastReadAt) {
    return this.messages.length;
  }

  return this.messages.filter(msg =>
    msg.sender.toString() !== userId &&
    msg.createdAt > participant.lastReadAt
  ).length;
};

messageSchema.methods.canUserAccess = function(userId) {
  return this.participants.some(p => p.user.toString() === userId && !p.hasLeft);
};

// Static methods
messageSchema.statics.findConversationsForUser = function(userId, options = {}) {
  const { page = 1, limit = 20, status = 'active' } = options;

  return this.find({
    'participants.user': userId,
    status,
    'participants.hasLeft': { $ne: true }
  })
  .populate('participants.user', 'profile.name profile.photo userType')
  .populate('vehicleId', 'title specifications.year specifications.make specifications.model media.photos.0.url pricing.listedPrice')
  .sort({ 'analytics.lastActivity': -1 })
  .limit(limit * 1)
  .skip((page - 1) * limit);
};

messageSchema.statics.findUnreadCount = function(userId) {
  return this.aggregate([
    {
      $match: {
        'participants.user': mongoose.Types.ObjectId(userId),
        'participants.hasLeft': { $ne: true },
        status: 'active'
      }
    },
    {
      $project: {
        participants: 1,
        messages: 1
      }
    },
    {
      $project: {
        unreadCount: {
          $size: {
            $filter: {
              input: '$messages',
              as: 'msg',
              cond: {
                $and: [
                  { $ne: ['$$msg.sender', mongoose.Types.ObjectId(userId)] },
                  {
                    $not: {
                      $anyElementTrue: {
                        $map: {
                          input: '$participants',
                          as: 'participant',
                          cond: {
                            $and: [
                              { $eq: ['$$participant.user', '$$msg.sender'] },
                              { $gt: ['$$participant.lastReadAt', '$$msg.createdAt'] }
                            ]
                          }
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      }
    },
    {
      $group: {
        _id: null,
        totalUnread: { $sum: '$unreadCount' }
      }
    }
  ]);
};

module.exports = mongoose.model('Message', messageSchema);